#!/bin/bash -e

source /opt/abacus-toolchain/install/setup
export OMP_NUM_THREADS=1

# Allow OpenMPI run as root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

CTEST_FLAGS="--test-dir build -V --timeout 1700 --output-on-failure"

ctest ${CTEST_FLAGS} -R integrated_test
ctest ${CTEST_FLAGS} -R MODULE_BASE
ctest ${CTEST_FLAGS} -R MODULE_IO
ctest ${CTEST_FLAGS} -R MODULE_HSOLVER
ctest ${CTEST_FLAGS} -R MODULE_CELL
ctest ${CTEST_FLAGS} -R MODULE_MD
ctest ${CTEST_FLAGS} -R MODULE_PSI
ctest ${CTEST_FLAGS} -R MODULE_RI
ctest ${CTEST_FLAGS} -R MODULE_ESTATE
ctest ${CTEST_FLAGS} -R MODULE_HAMILT
ctest ${CTEST_FLAGS} -R MODULE_PW
ctest ${CTEST_FLAGS} -R MODULE_LCAO
ctest ${CTEST_FLAGS} -R MODULE_AO
ctest ${CTEST_FLAGS} -R MODULE_NAO
ctest ${CTEST_FLAGS} -R MODULE_RELAX
ctest ${CTEST_FLAGS} -R MODULE_LR
ctest ${CTEST_FLAGS} -R 01_PW
ctest ${CTEST_FLAGS} -R 02_NAO_Gamma
ctest ${CTEST_FLAGS} -R 03_NAO_multik
ctest ${CTEST_FLAGS} -R 04_FF
ctest ${CTEST_FLAGS} -R 05_rtTDDFT
ctest ${CTEST_FLAGS} -R 06_SDFT
ctest ${CTEST_FLAGS} -R 07_OFDFT
ctest ${CTEST_FLAGS} -R 08_EXX
ctest ${CTEST_FLAGS} -R 09_DeePKS
ctest ${CTEST_FLAGS} -R 10_others
ctest ${CTEST_FLAGS} -R 17_DS_DFTU
# Check if we are missing anything
ctest ${CTEST_FLAGS} -E 'integrated_test|01_PW|02_NAO_Gamma|03_NAO_multik|04_FF|05_rtTDDFT|06_SDFT|07_OFDFT|08_EXX|09_DeePKS|10_others|11_PW_GPU|12_NAO_Gamma_GPU|13_NAO_multik_GPU|15_rtTDDFT_GPU|16_SDFT_GPU|17_DS_DFTU|MODULE_BASE|MODULE_IO|MODULE_HSOLVER|MODULE_CELL|MODULE_MD|MODULE_PSI|MODULE_ESTATE|MODULE_RI|MODULE_HAMILT|MODULE_PW|MODULE_LCAO|MODULE_AO|MODULE_NAO|MODULE_RELAX|MODULE_LR'

